// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	kreditplus "github.com/Bhinneka/kreditplus-go"
	mock "github.com/stretchr/testify/mock"
)

// KreditplusService is an autogenerated mock type for the KreditplusService type
type KreditplusService struct {
	mock.Mock
}

// GetCheckoutURL provides a mock function with given fields: param
func (_m *KreditplusService) GetCheckoutURL(param kreditplus.CheckoutRequest) (kreditplus.Response, error) {
	ret := _m.Called(param)

	var r0 kreditplus.Response
	if rf, ok := ret.Get(0).(func(kreditplus.CheckoutRequest) kreditplus.Response); ok {
		r0 = rf(param)
	} else {
		r0 = ret.Get(0).(kreditplus.Response)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(kreditplus.CheckoutRequest) error); ok {
		r1 = rf(param)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
